2.1.0/Dockerfile, 2.1.0/docker-entrypoint.sh, 2.1.0/local.ini, 2.1.0/vm.args
this PR adjusts the `2.0.0` setup to build `2.1.0`
```
$ cd 2.1.0
$ docker build -t couchdb:2.1.0 .
```
=> Add couchdb 2.1.0 docker image

2.1.0/Dockerfile, 2.1.0/vm.args
Without exposing more than 1 Erlang distribution port, clusters could only be 2 nodes large.
This PR expands the Erlang port distribution to the range 9100-9200, which should be large enough for nearly all use cases.
=> Allow Erlang distribution over 9100-9200 (2.1.0 only)

2.1.0/docker-entrypoint.sh
This applies the changes mentioned in #9. Hopefully this makes the Dockerfile ready to be released on docker-hub.
This can be tested by running a container based on the image and inspecting it with `docker exec` to verify that the `etc/local.d/secret.ini` file is successfully injected.
https://github.com/apache/couchdb-docker/issues/9
=> Make secret configurable via environment

1.6.1-couchperuser/Dockerfile, 1.6.1/Dockerfile, 2.1.0/Dockerfile, 2.1.0/docker-entrypoint.sh, dev/Dockerfile
Includes the following feedback from @yosifkit :
* Permission/ownership changes occur as often as possible in the layer in which the files are created to aid some Docker graph drivers
* Allow for simplified invocation. Any of the following work to specify additional CLI arguments:
* `docker run couchdb:2.1.0 /opt/couchdb/bin/couchdb +A 16`
* `docker run couchdb:2.1.0 couchdb +A 16`
* `docker run couchdb:2.1.0 +A 16`
* `docker run couchdb:2.1.0 -couch_ini /path/to/my/couch.ini ....`
* `gpg --verify` replaced with `gpg --batch --verify` everywhere.
=> Update with feedback from @yosifkit

2.1.0/local.ini
Node-local port (5986) was still bound to `localhost`, meaning it could not be forwarded outside of the container. This fixes that.
=> Bind node-local port to all container interfaces

2.1.0/Dockerfile, 2.1.0/vm.args, README.md
Port 5986 does not need to be exposed, can be accessed in other ways
as described in the README.
Port range for inet_dist_listen must be one port per erlang node.
Since Docker runs a single VM per container, a single value here is
sufficient.
=> Revert some changes for clustering

2.1.1/Dockerfile
HAProxy is included in the "dev-cluster" image to proxy requests to the three nodes deployed via that image. The production image runs a single CouchDB instance in each image and does not need or want a proxy server in the image.
Closes #56
=> Remove haproxy from production image

1.7.1/Dockerfile, 2.1.1/Dockerfile, dev/Dockerfile
Transition to a fixed uid and gid of 5984 (couchdb's default port) for the `couchdb` user.
Start the image, launch a bash shell into it and verify the uid and gid under `/etc/passwd` and `/etc/group`.
Closes #53
/cc @kocolosk
=> Use 5984:5984 as couchdb uid:gid, closes #53

README.md
README.md was misleading on the desired approach for making configuration changes, leading to PRs like #32. This makes it clearer that if you need more than you can get from a few simple env vars, you should be mounting `/opt/couchdb/etc/local.d` as a volume and persisting it to disk.
By specifying the `local.d` subdirectory we ensure that upstream image default changes to `/opt/couchdb/etc/default.ini`, as well as docker-specific upstream changes in `/opt/couchdb/etc/default.d`, are unaffected by externalisation of this volume.
Read it!
Closes #47
=> Improve README for configuration changes, closes #47

2.1.1/docker-entrypoint.sh, dev/docker-entrypoint.sh
Backports the fix for #81 and #82 to the 2.1.x image.
Also restored the check for an `[admins]` section in `default.d/*.ini` - can't hurt to be extra safe on this.
=> Backport fix for #81 and #82 to 2.1.x image

2.1.2/docker-entrypoint.sh
The docker entry-point.sh (CouchDB 2.1.1) add the admin credentials passed in docker start parameter.
If you use a config file named docker.ini and forget to add a new line at the end of file, it will be add next to the last line.
Name the config file docker.ini is maybe not a good idea, but i lost time to understand this.
(Same thing for COUCHDB_SECRET)
The last lines of docker.ini have to be 
```
[chttpd]
bind_address = 0.0.0.0;
[admins]
couchdb_user = couchdb_password
```
```
[chttpd]
bind_address = 0.0.0.0;[admins]
couchdb_user = couchdb_password
```
In docker entrypoint : 
`printf "[admins]\n%s = %s\n" "$COUCHDB_USER" "$COUCHDB_PASSWORD" >> /opt/couchdb/etc/local.d/docker.ini`
change it to :
` printf "\n[admins]\n%s = %s\n" "$COUCHDB_USER" "$COUCHDB_PASSWORD" >> …
=> [issue #89] End of line expected in docker.ini

2.1.2/Dockerfile
This gets us to Erlang 19.2, which is new enough to support apache/couchdb#1392 and useful dirty schedulers. It was time to get off of `debian:jessie` anyway.
This is also prep work for the imminent 2.2.0 release of CouchDB.
=> Use debian stretch, closes #91

2.2.0/Dockerfile, README.md, dev/Dockerfile
* use full pgp hash for `--recv-keys`
* put key in `/etc/apt/trusted.gpg.d` and don't use `apt-key add`
* drop mention of 1.x images in README
=> Feedback from @tianon + deprecate 1.x images

2.3.0/Dockerfile
See https://github.com/docker-library/official-images/pull/5149#issuecomment-445042403:
* Remove dupliate attempt to install `gpg`
* Purge `wget` after we're done with it, in the same layer we retrieved it
* Do not `wget | apt-key` but instead fetch gpg key from public key servers, then add to the apt keychain
* Do not always expose `/opt/couchdb/etc/local.d` as a volume; let the user make that decision themselves
=> Feedback from Docker official images

.github/ISSUE_TEMPLATE.md, README.md
This normalises our README with the one in https://github.com/docker-library/docs/tree/master/couchdb while retaining the Apache-specific sections (dev image, maintainer upload instructions).
It also updates our issue template to warn users to file issues at apache/couchdb instead of here if they're experiencing an issue with CouchDB, not specifically with the Docker container.
=> Documentation updates for 2.3.0

2.3.0/Dockerfile, 2.3.1/Dockerfile, dev/Dockerfile
See #132 - this is the revised version.
Already +1 by @kocolosk .
=> Speed up startup time, fixes #131

.travis.yml, 1.7.2-couchperuser/Dockerfile, 1.7.2/Dockerfile, README.md
In rebuilding 1.7.2 I found a couple of inconsistencies that were leading to broken images.
Patching this allowed the builds to complete.
This is *NOT* a return to support for 1.7.2, just a quick fix to keep the builds working.
=> Fix broken 1.7.2 build process

dev-cluster/Dockerfile, dev/Dockerfile
Fixes the `dev` containers which were missing `setuptools` (perhaps lots in the transition to python 3).
```
docker build -t couchdb:dev dev
docker build -t couchdb:dev-cluster dev-cluster
```
=> add setuptools to dev images

2.3.1/Dockerfile, 2.3.1/docker-entrypoint.sh, README.md
Enables the CouchDB container to run as a non-root / user-specified uid. For now, I've only modified the 2.3.1 container but if the approach is accepted we can easily backport it.
Specifically, this:
* Adds guards around entrypoints commands that require root (as suggested in #147)
* Broadens permissions within the container filesystem to allow access by non-couchdb users.
* Adds an example to the documentation which specifies `--user`.
Build the container locally:
```
docker build -t couchdb:2.3.1 2.3.1
```
Run the container as a custom user
```
docker run --user <user> --name mycouch -p 5984:5984 -d couchdb:2.3.1
```
or, run the container as a custom user with a mounted data volume:
```
mkdir /Users/<user>/temp/couchdb-data
docker run --user <user> --name mycouch -v …
```
=> allow running as arbitrary uid

.travis.yml, 2.3.1-ubi7/Dockerfile, 2.3.1-ubi7/bintray-apache-couchdb-rpm.repo, 2.3.1-ubi7/imeyer_runit.repo, 2.3.1-ubi7/licenses/LICENSE, 2.3.1-ubi7/resources/10-docker-default.ini, 2.3.1-ubi7/resources/docker-entrypoint.sh, 2.3.1-ubi7/resources/run, 2.3.1-ubi7/resources/vm.args
This PR supersedes #146 to contribute the latest UBI based container, which now makes use of runit to start/stop the CouchDB process. The docker entry point has been adapted so custom parameters can be passed to couch as with the other CouchDB Dockerfiles.
Also, includes changes necessary for Red Hat Certification:
- licenses folder
- Specific labels
- couchdb user moved to root group
- runit can be launched by any userid
=> Ubi with runit

.travis.yml, dev-cluster/Dockerfile, dev/Dockerfile, dev/docker-entrypoint.sh
* Move dev and dev-cluster build to debian-buster
* Transition to node 10 from node 8
* Updated libicu to match
* Move to SM60
* Intended for use on amd64 and ppc64le only; arm will break with SM60
Part of #163
=> dev: debian-buster, node 10, SM60

dev/Dockerfile
8bed55760e744ef1e4821fc8c9304f25676cf237 surprised users of the image by overriding the configuration arguments.
Since we require SM60 at present for this image, this breaks out that configuration aspect to a new `ARG` and defaults it to 60.
This also reverts the default `-c` as requested.
`docker build -t couchdb:dev dev`
https://github.com/apache/couchdb-docker/pull/165#discussion_r375025684
=> separately parametrize SM version

dev/docker-entrypoint.sh
The container won't stop anymore if admin users are present in _/opt/couchdb/etc/local.ini_.
Create a local.ini with at least one user in [admins]. Run `docker run -d --name my-couchdb -v <path-to-my>/local.ini:/opt/couchdb/etc/local.ini couchdb:<3.0.0-fix>`.
Fixes #172
=> Check /opt/couchdb/etc/*.ini files

2.3.1/docker-entrypoint.sh, 3.0.1/docker-entrypoint.sh, 3.1.0/docker-entrypoint.sh, dev/docker-entrypoint.sh
This re-fixes #172 with the fix proposed in the description to #180 , but does so *without* grepping `default.ini`. This is probably an innocuous grep in all but the final grep, which looks for an `[admins]` section followed by a non-comment. Arguably, this might show up someday in `default.ini` so best to explicitly list _only_ `/opt/couchdb/etc/local.ini`.
/cc @brOOper
=> Only check local.ini to fix #172

README.md
Adds information about ports exposed by image for cluster instances. 
N/A
N/A
N/A
=> Add information about exposed cluster related ports

3.1.0-ubi-clouseau/Dockerfile, 3.1.0-ubi-clouseau/bintray-apache-couchdb-rpm.repo, 3.1.0-ubi-clouseau/imeyer_runit.repo, 3.1.0-ubi-clouseau/licenses/LICENSE, 3.1.0-ubi-clouseau/resources/10-docker-default.ini, 3.1.0-ubi-clouseau/resources/clouseau/clouseau.ini, 3.1.0-ubi-clouseau/resources/clouseau/clouseau.sh, 3.1.0-ubi-clouseau/resources/clouseau/log4j.properties, 3.1.0-ubi-clouseau/resources/docker-entrypoint.sh, 3.1.0-ubi-clouseau/resources/pre_stop, 3.1.0-ubi-clouseau/resources/run, 3.1.0-ubi-clouseau/resources/run_clouseau, 3.1.0-ubi-clouseau/resources/vm.args
This adds a Dockerfile which contains both CouchDB and Clouseau
in a single container. This is useful because in most containerized
environments, EPMD runs in the CouchDB container; restarting the
CouchDB container can therefore lead to Clouseau becoming orphaned
because EPMD is also killed.
The container is based on the Red Hat UBI and uses runit to supervise
both CouchDB and Clouseau. UBI is used mostly for familiarity (this
is how we build a combined container at IBM), but it serves as a
reference for anybody looking to port to other base images.
The dockerfile entrypoint is modified to configure CouchDB and Clouseau
in an Erlang cluster. It's equally possible to run the container in
e.g. Kubernetes or Docker Compose without the dockerfile entrypoint;
the user would then need to write …
=> Combined CouchDB / Clouseau dockerfile

pull-all-couchdbdev-docker
https://www.docker.com/pricing/resource-consumption-updates means older images that aren't active go away soon. We want to keep our old CI workflows, just in case.
Run the new shell script!
=> Add script that keeps old couchdbdev docker images alive

dev-cluster/Dockerfile, dev/Dockerfile
Since from apache/couchdb#3224 CouchDB moved from `master` to `main` but the Dockerfile still refers default branch to be`master` and fails during the build.
The changes will fix the failing dev builds.
=> Update Dockerfile to use `main` branch rather than master

build.sh
See https://lists.apache.org/thread.html/r1a5ebf1b8f3c3513f54dc9212e0fcc5e48d96ad7a2beb75d4c946718%40%3Cdev.couchdb.apache.org%3E for discussion.
Once this lands, a similar PR will be made against downstream Docker official images.
=> Drop ppc64le until suitable CI replacement identified

.travis.yml, 2.3.1-ubi/Dockerfile, 2.3.1-ubi/bintray-apache-couchdb-rpm.repo, 2.3.1-ubi/couchdb.repo, 2.3.1/Dockerfile, 3.1.1-ubi-clouseau/Dockerfile, 3.1.1-ubi-clouseau/bintray-apache-couchdb-rpm.repo, 3.1.1-ubi-clouseau/couchdb.repo, 3.1.1-ubi/Dockerfile, 3.1.1-ubi/bintray-apache-couchdb-rpm.repo, 3.1.1-ubi/couchdb.repo, 3.1.1/Dockerfile, build.sh, dev/Dockerfile
Replaces old bintray references with new artifactory ones.
Replaces GPG key retrieval with direct pull from couchdb.apache.org.
Build per usual process
Closes #201
=> Update with jfrog artifactory repo

.travis.yml, 3.2.1/10-docker-default.ini, 3.2.1/Dockerfile, 3.2.1/docker-entrypoint.sh, 3.2.1/vm.args, README.md
Docker images pushed as 3.2.1, 3.2, 3 and latest
```
./build.sh push 3.2.1
Created manifest list docker.io/apache/couchdb:3.2.1
sha256:baa32c5386eb440b17df45abad6ec76322890cc8272a76f78fbd48e3a70f5618
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 2617,
"digest": "sha256:932d61826a5ce5502ebdcfc69f36480286af026bd5c3a136682562bc733ab18c",
"platform": {
"architecture": "amd64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 2617,
"digest": "sha256:41973db85158829fa9a7a56ce7660e7a10c74f813cf720e95e32169b60c46251",
"platform": {
"architecture": "arm64",
"os": "linux",
"variant": "v8"
}
}
]
}
```
=> Version 3.2.1

3.2.0-ubi-clouseau/resources/docker-entrypoint.sh, 3.2.0/docker-entrypoint.sh, 3.2.1/docker-entrypoint.sh, dev/docker-entrypoint.sh
With CouchDB 3.2+ the `secret` has moved from `[couch_httpd_auth]` to the `[chttpd_auth]` section. See the [documentation](https://docs.couchdb.org/en/stable/config/auth.html#chttpd_auth/secret).
The cluster setup fails with the reason `Cluster setup unable to sync admin passwords` when using the `couchdb:3.2.1` Docker image and environment variable `COUCHDB_SECRET=a-secret`.
This pull request makes the entrypoint script use the correct config section to configure the provided secret.
A rebuild of the Docker image with the fixed docker-entrypoint.sh makes the cluster setup succeed.
- [n/a] Changes are covered by tests;
- [n/a] Documentation reflects the changes;
=> fix(entrypoint): move secret from [couch_httpd_auth] to [chttpd_auth]

3.2.1/docker-entrypoint.sh, README.md, dev/docker-entrypoint.sh
This just makes it simpler to install an Erlang distribution cookie. If the COUCHDB_ERLANG_COOKIE environment variable is set, the entry point script will take its contents and write them as ~/.erlang.cookie.
The `-setcookie` approach in ERL_FLAGS still works, and will take precedence over the COUCHDB_ERLANG_COOKIE.
Build the image and then start a container like
```
docker run --env COUCHDB_ERLANG_COOKIE=foobaz --env COUCHDB_USER=admin --env COUCHDB_PASSWORD=foo --env NODENAME=localhost apache/couchdb:latest
```
Fire up a shell on the container and you should see `/opt/couchdb/.erlang.cookie` with contents 'foobaz'.
=> Listen for COUCHDB_ERLANG_COOKIE and write it down

3.2.1/Dockerfile, build.sh
Several modernizations to our latest production image:
1. Re-add ppc64le support to the platform matrix, as we [do run this in CI](https://github.com/apache/couchdb/blob/e4b8a4624fc7ae09b4649aac9a8d68226208cd8b/build-aux/Jenkinsfile.full#L69-L74) once more.
2. Bump Debian 10 -> Debian 11
3. Bump Erlang 20 -> Erlang 23
4.  Bump SpiderMonkey 60 -> SpiderMonkey 78
- We have been running Debian 11 + Erlang 23 in Jenkins for PRs since apache/couchdb-ci#30
- We also started using Erlang 23 as the default for Full Platform Builds in apache/couchdb#3903
- Images constructed using this branch are already posted to https://hub.docker.com/r/apache/couchdb/tags
Fixes #213
=> Restore ppc64le support, update Debian+Erlang+SpiderMonkey

3.2.2/docker-entrypoint.sh, 3.3.1/docker-entrypoint.sh, dev/docker-entrypoint.sh
Why:
In https://github.com/apache/couchdb-docker/pull/234 we moved from using `gosu` to `setpriv` to step down from the root user to the couchdb user.
There is a behavioural difference between and `gosu` and `setpriv` in that `gosu` will [set the $HOME environment variable](https://github.com/tianon/gosu/blob/master/setup-user.go#L45) to that of the target user.
Without this behaviour, `couchdb` includes the root user home directory (`/root`) in various search paths and crashes because it doesn't have read permissions.
How:
Explicitly set `$HOME` to the `couchdb` user home directory before we execute as the `couchdb` user, replicating the `gosu` behaviour.
The easiest reproducer is:
```
$ docker run -it -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password -eNODENAME=foo couchdb:3.2.2 …
```
=> fix: set $HOME when stepping down from root

README.md
* Use `build.sh buildx` otherwise we risk pushing only the architecture image for the host where build and push is run.
* Update readme file with buildx instructions example
* master -> main references
=> Update release instructions for 3.3.x release series

build.sh
Since the s390x .deb binary on debian:bullseye is released from v3.3.2 afterwards and all pre-requisites mentioned in https://github.com/apache/couchdb-docker/issues/67#issue-293689385 are available now, this PR aims to add s390x support to CouchDB docker image.
https://github.com/apache/couchdb-docker#how-to-use-this-image
https://docs.couchdb.org/en/stable/intro/tour.html
I've built the multi-arch docker image on an Intel VM after applying the code change in this PR and verified the generated s390x image on a s390x VM. It worked fine.
https://github.com/apache/couchdb-docker/issues/67
=> Add s390x support to CouchDB docker image

dev/Dockerfile
This change fixes the build and includes the following improvements:
- Move to Debian Bookworm because that is the release that includes OTP 25 out-of-the-box, which is required by `main`.
- Use a "slim" base image.
- Update SpiderMonkey to 78 and make it possible to build the image natively on `arm64` (such as Apple M1).
- Avoid explicit `pip3 install` because that is not endorsed by Debian packaging.  The Python package versions available in Bookworm shall suffice.
- Remove installation of extra FoundationDB packages — they seem to be gone, which breaks the build for every platform.
- Bump Node.js to 18, the latest recommend version.  This is also included in Bookworm.  Base the installation of NPM and Grunt on Debian packages.
- Chase changes in the `configure` script.
=> fix: unbreak build

README.md
Add additional configuration to setup different container running `couchdb:3.4.1` and `couchdb:3.4.1-nouveau` images.
Please check if the information added is correct.
=> docs(nouveau): add additional nouveau ini config

build.sh
We only use buildx
Remove auto buildx setup. That breaks users' buildx contexts and leaves it modified. Docker nowadays setups setup buildx fairly well and there is no need to do all the experimental stuff.
=> Clean up unused bits from build.sh

3.5.0-nouveau/Dockerfile, 3.5.0-nouveau/nouveau.yaml, 3.5.0/10-docker-default.ini, 3.5.0/Dockerfile, 3.5.0/docker-entrypoint.sh, 3.5.0/vm.args, README.md
Images already pushed as:
```
./build.sh buildx 3.5.0
./build.sh buildx 3.5.0 as 3.5
./build.sh buildx 3.5.0 as 3
./build.sh buildx 3.5.0 as latest
```
https://hub.docker.com/repository/docker/apache/couchdb/tags
=> New release 3.5.0
